.PHONY: all
all:
	node --experimental-vm-modules --no-warnings -- ../lang/bin/serif.js '$(CURDIR)/src' '$(CURDIR)/lib' '$(CURDIR)/src/scripts/everything.serif'
	node -- '$(CURDIR)/lib/scripts/everything.js'
