{:.htaccess ".htaccess"
 :adobe "Adobe"
 :accessibility "accessibility"
 :applescript "AppleScript"
 :architecture "architecture"
 :art "art"
 :best-practice "best practice"
 :bookmarklets "bookmarklets"
 :coda "Coda"
 :cs3 "CS3"
 :css "CSS"
 :css3 "CSS3"
 :design "design"
 :django "Django"
 :dom "DOM"
 :emacs "Emacs"
 :flash "Flash"
 :gmail "Gmail"
 :google "Google"
 :google-calendar "google calendar"
 :google-chrome "Google Chrome"
 :hacks "hacks"
 :hashify "Hashify"
 :hg "hg"
 :html "HTML"
 :html5 "HTML5"
 :i18n "i18n"
 :icons "icons"
 :ie "IE"
 :illustrator "Illustrator"
 :iphone "iPhone"
 :javascript "JavaScript"
 :jquery "jQuery"
 :keyboard-shortcuts "keyboard shortcuts"
 :localization "localization"
 :mercurial "Mercurial"
 :mac-os-x "Mac OS X"
 :mango "Mango"
 :markdown "Markdown"
 :meaningful-markup "meaningful markup"
 :mootools "MooTools"
 :mysql "MySQL"
 :node.js "Node.js"
 :optimization "optimization"
 :performance "performance"
 :photoshop "Photoshop"
 :php "PHP"
 :productivity "productivity"
 :programming "programming"
 :prototype "Prototype"
 :python "Python"
 :regex "regex"
 :regular-expressions "regular expressions"
 :ruby "Ruby"
 :safari "Safari"
 :script.aculo.us "script.aculo.us"
 :search "search"
 :security "security"
 :seo "SEO"
 :showdown "Showdown"
 :sms "SMS"
 :snow-leopard "Snow Leopard"
 :solarized "Solarized"
 :sproutcore "SproutCore"
 :sql "SQL"
 :syntax-highlighting "syntax highlighting"
 :syntaxhighlighter "SyntaxHighlighter"
 :terminal.app "Terminal.app"
 :textmate "TextMate"
 :twitter "Twitter"
 :typography "typography"
 :ux "UX"
 :video "video"
 :webkit "WebKit"
 :windows "Windows"
 :wmd "wmd"
 :wordpress "WordPress"}
